add vra_deployment.recreate_if_expired_at attribute, fix #473
vmware/terraform-provider-vra pull request #514
Opened 2024-01-22 13:09 UTC by azrdev

2024-04-18 07:50 UTC, azrdev commented
DCO signed. before merge, please note the alternatives described in the linked issue comment

2024-08-01 07:20 UTC, azrdev commented
What is missing for this to be merged (or #473 to be fixed some other way)? Can I do something?

2024-11-15 10:53 UTC, azrdev commented
Rebased to current main due to merge conflict. @tenthirtyam you assigned me, but I have no permissions to merge here / need a review by some maintainer. Who's able to do that?

2024-12-03 16:36 UTC, tenthirtyam requested changes
Suggesting a change as follows that would be a bit more simplified and idiomatic.

```go
CustomizeDiff: customdiff.ForceNewIf(
    "recreate_if_expired_at",
    func(ctx context.Context, d *schema.ResourceDiff, meta interface{}) bool {
        planTime, valid := getParsedTime(d, "recreate_if_expired_at")
        if !valid {
            return false
        }
        expirationTime, valid := getParsedTime(d, "lease_expire_at")
        if !valid {
            return false
        }
        return expirationTime.Before(planTime)
    }
),
```

and

```go
func getParsedTime(d *schema.ResourceDiff, key string) (time.Time, bool) {
    timeStr, ok := d.GetOk(key)
    if !ok {
        log.Printf("[INFO] Missing or invalid time string for key %s: %#v", key, timeStr)
        return time.Time{}, false
    }
    parsedTime, err := strfmt.ParseDateTime(timeStr.(string))
    if err != nil {
        log.Printf("[INFO] Failed to parse DateTime for key %s: %#v", key, timeStr)
        return time.Time{}, false
    }
    return time.Time(parsedTime), true
}
```

2025-03-13 00:33 UTC, closed without merging